// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfvR0tgtS7DUbg9ZOfwnHg7MW7YH4FLSg',
    appId: '1:462260908466:android:a3e5099eb1debb5b4034ab',
    messagingSenderId: '462260908466',
    projectId: 'electronichealthapp',
    databaseURL: 'https://electronichealthapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electronichealthapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGl-cv-VjpHDMgeYZYCBNaTO7jy71V8RM',
    appId: '1:462260908466:ios:261415e3a88647264034ab',
    messagingSenderId: '462260908466',
    projectId: 'electronichealthapp',
    databaseURL: 'https://electronichealthapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electronichealthapp.appspot.com',
    iosClientId: '462260908466-99adpkm8gccqk4pk1a2fe4ek9ananftu.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicHealthApp',
  );
}
